# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  chat2db = {
    pname = "chat2db";
    version = "5.3.4";
    src = fetchurl {
      url = "https://github.com/OtterMind/Chat2DB/releases/download/v5.3.4/Chat2DB-Community-5.3.4-arm64.dmg";
      sha256 = "sha256-edkGPrsdHXIIBsWeaigSkWUdBthaAhe7Mw5Ylm8a0f0=";
    };
    github = "OtterMind/Chat2DB";
    tagPrefix = "v";
  };
  cli-proxy-api = {
    pname = "cli-proxy-api";
    version = "7.2.140";
    src = fetchurl {
      url = "https://github.com/router-for-me/CLIProxyAPI/releases/download/v7.2.140/CLIProxyAPI_7.2.140_darwin_aarch64.tar.gz";
      sha256 = "sha256-R6pSnimnWAQoOtRCBjkOHDWykOLE4ZFzm9gnWUYex+c=";
    };
    github = "router-for-me/CLIProxyAPI";
    tagPrefix = "v";
  };
  cursor-cli = {
    pname = "cursor-cli";
    version = "2026.08.11-e8db854";
    src = fetchurl {
      url = "https://downloads.cursor.com/lab/2026.08.11-e8db854/darwin/arm64/agent-cli-package.tar.gz";
      sha256 = "sha256-RgRNbXvL17SaDPHNAapMp5qqLqXyx6MpZfwOvimEF5A=";
    };
    versionUrl = "https://cursor.com/install";
    versionRegex = "downloads.cursor.com/lab/([^/]+)/";
  };
  genoffice = {
    pname = "genoffice";
    version = "0.7.793";
    src = fetchurl {
      url = "https://github.com/genspark-ai/genoffice/releases/download/v0.7.793/GenOffice-0.7.793-arm64.dmg";
      sha256 = "sha256-nx0Hg2gwHrp4Q+Q122GgBQH/DzVtkhOWpeUL8KtP88I=";
    };
    github = "genspark-ai/genoffice";
    tagPrefix = "v";
  };
  logseq-nightly = {
    pname = "logseq-nightly";
    version = "2.0.1-alpha+nightly.20260819";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/nightly/Logseq-darwin-arm64-2.0.1-alpha+nightly.20260819.zip";
      sha256 = "sha256-t4qialn6gSLvlVGUvVbDfFuF4+6rYJjL6/51OfqDlks=";
    };
    versionUrl = "https://github.com/logseq/logseq/releases/expanded_assets/nightly";
    versionRegex = "Logseq-darwin-arm64-([0-9A-Za-z.+-]+nightly[.][0-9]+)[.]zip";
  };
  vite-plus = {
    pname = "vite-plus";
    version = "0.2.9";
    src = fetchurl {
      url = "https://github.com/voidzero-dev/vite-plus/releases/download/v0.2.9/vp-aarch64-apple-darwin.tar.gz";
      sha256 = "sha256-Gp/pHxiq7hU2+nal2WlGHGLM81YrOUMYC7LZz13HsI0=";
    };
    github = "voidzero-dev/vite-plus";
    tagPrefix = "v";
  };
}
