import { Effect } from "effect";
import { FileSystem } from "effect/FileSystem";
import { SYSTEM_IDS, type NodeId } from "@kb/model";
import { query } from "@kb/query";
import {
  resolveSavedQueryFile,
} from "../saved-query.ts";
import type { KbContext } from "@kb/contracts";
import { KbCtx } from "@kb/contracts";
import { templates, type TemplateContext } from "./templates.ts";
import { DocsError, type LoadedView } from "./views.ts";

export { DocsError, ViewSpecSchema, loadViewsEffect } from "./views.ts";
export { templates, renderText } from "./templates.ts";
export type { TemplateContext, TemplateFn } from "./templates.ts";

export const GENERATED_HEADER = "<!-- generated by kb; do not edit -->";

function templateContext(ctx: KbContext): TemplateContext {
  return {
    nodes: ctx.qdb.nodes,
    fieldIdByName(name: string): NodeId | undefined {
      const matches = ctx.nodes.filter(
        (n) =>
          n.text === name &&
          (n.props[SYSTEM_IDS.typeField] ?? []).some(
            (v) => v.t === "ref" && v.v === SYSTEM_IDS.field,
          ),
      );
      return matches.length === 1 ? matches[0]!.id : undefined;
    },
  };
}

const viewEdnEffect = Effect.fn("docs.viewEdn")(
  function* (
    view: LoadedView,
  ): Effect.fn.Return<string, DocsError, KbCtx | FileSystem> {
    if (view.spec.query !== undefined) return view.spec.query;
    const ctx = yield* KbCtx;
    const name = view.spec.savedQuery!;
    const path = resolveSavedQueryFile(ctx.root, name);
    if (!path) {
      return yield* Effect.fail(
        new DocsError(
          "invalid_input",
          `invalid saved query name: ${name}`,
          { view: view.name, savedQuery: name },
        ),
      );
    }
    const fs = yield* FileSystem;
    const edn = yield* fs.readFileString(path).pipe(
      Effect.mapError(
        () =>
          new DocsError("not_found", `saved query not found: ${name}`, {
            view: view.name,
            path,
          }),
      ),
    );
    return edn;
  },
);

/** Render one view to its final file content (header + template output). */
export const renderViewEffect = Effect.fn("docs.renderView")(
  function* (
    view: LoadedView,
  ): Effect.fn.Return<string, DocsError, KbCtx | FileSystem> {
    const ctx = yield* KbCtx;
    const template = templates[view.spec.template];
    if (!template) {
      return yield* Effect.fail(
        new DocsError(
          "invalid_input",
          `unknown template: ${view.spec.template}`,
          { view: view.name, known: Object.keys(templates).sort() },
        ),
      );
    }
    const edn = yield* viewEdnEffect(view);
    const rows = yield* Effect.try({
      try: () => query(ctx.qdb, edn) as unknown[][],
      catch: (err) =>
        new DocsError(
          "invalid_input",
          `invalid datalog query in view ${view.name}: ${err instanceof Error ? err.message : String(err)}`,
          { view: view.name },
        ),
    });
    const body = template(rows, templateContext(ctx));
    return `${GENERATED_HEADER}\n\n${body.trimEnd()}\n`;
  },
);
