import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { z } from "zod";
import type { ActionDefinition } from "../../shared/contracts.ts";
import { SYSTEM_IDS, type NodeId } from "../../foundation/model.ts";
import { query } from "../../foundation/query/index.ts";
import type { KbContext } from "../../context.ts";
import { templates, type TemplateContext } from "./templates.ts";
import { DocsError, loadViews, type LoadedView } from "./views.ts";

export { DocsError, ViewSpecSchema, loadViews } from "./views.ts";
export { templates, renderText } from "./templates.ts";
export type { TemplateContext, TemplateFn } from "./templates.ts";

export const GENERATED_HEADER = "<!-- generated by kb; do not edit -->";

export const docsMaterializeDef = {
  id: "docs.materialize",
  title: "Materialize docs",
  description:
    "Run view specs from .kb/views (all, or one by name) and write generated markdown",
  mode: "apply" as const,
  inputSchema: z.object({
    view: z.string().optional(),
  }),
  outputSchema: z.object({
    written: z.array(z.object({ view: z.string(), output: z.string() })),
  }),
} satisfies ActionDefinition;

export const docsCheckDef = {
  id: "docs.check",
  title: "Check docs",
  description:
    "Materialize views to memory and diff against disk; report clean/stale/missing per view",
  mode: "read" as const,
  inputSchema: z.object({
    view: z.string().optional(),
  }),
  outputSchema: z.object({
    clean: z.boolean(),
    views: z.array(
      z.object({
        view: z.string(),
        output: z.string(),
        status: z.enum(["clean", "stale", "missing"]),
      }),
    ),
  }),
} satisfies ActionDefinition;

function templateContext(ctx: KbContext): TemplateContext {
  return {
    nodes: ctx.qdb.nodes,
    fieldIdByName(name: string): NodeId | undefined {
      const matches = ctx.nodes.filter(
        (n) =>
          n.text === name &&
          (n.props[SYSTEM_IDS.typeField] ?? []).some(
            (v) => v.t === "ref" && v.v === SYSTEM_IDS.field,
          ),
      );
      return matches.length === 1 ? matches[0]!.id : undefined;
    },
  };
}

async function viewEdn(ctx: KbContext, view: LoadedView): Promise<string> {
  if (view.spec.query !== undefined) return view.spec.query;
  const path = join(ctx.root, ".kb", "queries", `${view.spec.savedQuery}.edn`);
  try {
    return await readFile(path, "utf8");
  } catch {
    throw new DocsError(
      "not_found",
      `saved query not found: ${view.spec.savedQuery}`,
      { view: view.name, path },
    );
  }
}

/** Render one view to its final file content (header + template output). */
export async function renderView(
  ctx: KbContext,
  view: LoadedView,
): Promise<string> {
  const template = templates[view.spec.template];
  if (!template) {
    throw new DocsError(
      "invalid_input",
      `unknown template: ${view.spec.template}`,
      { view: view.name, known: Object.keys(templates).sort() },
    );
  }
  const edn = await viewEdn(ctx, view);
  const rows = query(ctx.qdb, edn) as unknown[][];
  const body = template(rows, templateContext(ctx));
  return `${GENERATED_HEADER}\n\n${body.trimEnd()}\n`;
}

export async function docsMaterialize(
  ctx: KbContext,
  input: z.infer<typeof docsMaterializeDef.inputSchema>,
): Promise<{ written: { view: string; output: string }[] }> {
  const views = await loadViews(ctx.root, input.view);
  const written: { view: string; output: string }[] = [];
  for (const view of views) {
    const content = await renderView(ctx, view);
    const path = join(ctx.root, view.spec.output);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, content, "utf8");
    written.push({ view: view.name, output: view.spec.output });
  }
  return { written };
}

export async function docsCheck(
  ctx: KbContext,
  input: z.infer<typeof docsCheckDef.inputSchema>,
): Promise<{
  clean: boolean;
  views: { view: string; output: string; status: "clean" | "stale" | "missing" }[];
}> {
  const views = await loadViews(ctx.root, input.view);
  const results: {
    view: string;
    output: string;
    status: "clean" | "stale" | "missing";
  }[] = [];
  for (const view of views) {
    const expected = await renderView(ctx, view);
    let status: "clean" | "stale" | "missing";
    try {
      const actual = await readFile(join(ctx.root, view.spec.output), "utf8");
      status = actual === expected ? "clean" : "stale";
    } catch {
      status = "missing";
    }
    results.push({ view: view.name, output: view.spec.output, status });
  }
  return {
    clean: results.every((r) => r.status === "clean"),
    views: results,
  };
}
