import { SYSTEM_IDS, type NodeId } from "../../foundation/model.ts";
import { query } from "../../foundation/query/index.ts";
import {
  readSavedQuery,
  resolveSavedQueryFile,
} from "../../foundation/saved-query.ts";
import type { KbContext } from "../../context.ts";
import { templates, type TemplateContext } from "./templates.ts";
import { DocsError, type LoadedView } from "./views.ts";

export { DocsError, ViewSpecSchema, loadViews } from "./views.ts";
export { templates, renderText } from "./templates.ts";
export type { TemplateContext, TemplateFn } from "./templates.ts";

export const GENERATED_HEADER = "<!-- generated by kb; do not edit -->";

function templateContext(ctx: KbContext): TemplateContext {
  return {
    nodes: ctx.qdb.nodes,
    fieldIdByName(name: string): NodeId | undefined {
      const matches = ctx.nodes.filter(
        (n) =>
          n.text === name &&
          (n.props[SYSTEM_IDS.typeField] ?? []).some(
            (v) => v.t === "ref" && v.v === SYSTEM_IDS.field,
          ),
      );
      return matches.length === 1 ? matches[0]!.id : undefined;
    },
  };
}

async function viewEdn(ctx: KbContext, view: LoadedView): Promise<string> {
  if (view.spec.query !== undefined) return view.spec.query;
  const name = view.spec.savedQuery!;
  const path = resolveSavedQueryFile(ctx.root, name);
  if (!path) {
    throw new DocsError(
      "invalid_input",
      `invalid saved query name: ${name}`,
      { view: view.name, savedQuery: name },
    );
  }
  const edn = await readSavedQuery(ctx.root, name);
  if (edn === null) {
    throw new DocsError(
      "not_found",
      `saved query not found: ${name}`,
      { view: view.name, path },
    );
  }
  return edn;
}

/** Render one view to its final file content (header + template output). */
export async function renderView(
  ctx: KbContext,
  view: LoadedView,
): Promise<string> {
  const template = templates[view.spec.template];
  if (!template) {
    throw new DocsError(
      "invalid_input",
      `unknown template: ${view.spec.template}`,
      { view: view.name, known: Object.keys(templates).sort() },
    );
  }
  const edn = await viewEdn(ctx, view);
  const rows = query(ctx.qdb, edn) as unknown[][];
  const body = template(rows, templateContext(ctx));
  return `${GENERATED_HEADER}\n\n${body.trimEnd()}\n`;
}
