import { Effect } from "effect";
import { SYSTEM_IDS, present, type NodeId } from "@kb/model";

import type { KbContext, TemplateContext } from "@kb/contracts";
import { KbCtx, SavedQueries, TemplateRegistry } from "@kb/contracts";
import { DocsError, type LoadedView } from "./views.ts";

export { DocsError, loadViewsEffect } from "./views.ts";

export const GENERATED_HEADER = "<!-- generated by kb; do not edit -->";

function templateContext(ctx: KbContext): TemplateContext {
  return {
    nodes: new Map([...ctx.index.allNodes()].map((n) => [n.id, n])),
    fieldIdByName(name: string): NodeId | undefined {
      const matches = ctx.nodes.filter(
        (n) =>
          n.text === name &&
          (n.props[SYSTEM_IDS.typeField] ?? []).some(
            (v) => v.t === "ref" && v.v === SYSTEM_IDS.field,
          ),
      );
      return matches.length === 1 ? present(matches[0], `field named ${name}`).id : undefined;
    },
  };
}

const viewEdnEffect = Effect.fn("docs.viewEdn")(function* (
  view: LoadedView,
): Effect.fn.Return<string, DocsError, SavedQueries> {
  if (view.spec.query !== undefined) return view.spec.query;
  const name = present(view.spec.savedQuery, `view ${view.name} savedQuery`);
  const queries = yield* SavedQueries;
  const edn = yield* queries.read(name).pipe(
    Effect.mapError(
      () =>
        new DocsError("invalid_input", `invalid saved query name: ${name}`, {
          view: view.name,
          savedQuery: name,
        }),
    ),
  );
  if (edn === null) {
    return yield* Effect.fail(
      new DocsError("not_found", `saved query not found: ${name}`, {
        view: view.name,
        savedQuery: name,
      }),
    );
  }
  return edn;
});

/** Render one view to its final file content (header + template output). */
export const renderViewEffect = Effect.fn("docs.renderView")(function* (
  view: LoadedView,
): Effect.fn.Return<string, DocsError, KbCtx | SavedQueries | TemplateRegistry> {
  const ctx = yield* KbCtx;
  const templates = yield* TemplateRegistry;
  const template = templates.get(view.spec.template);
  if (!template) {
    return yield* Effect.fail(
      new DocsError("invalid_input", `unknown template: ${view.spec.template}`, {
        view: view.name,
        known: [...templates.keys()].toSorted(),
      }),
    );
  }
  const edn = yield* viewEdnEffect(view);
  const rows = yield* Effect.try({
    try: () => ctx.index.runDatalog(edn),
    catch: (err) =>
      new DocsError(
        "invalid_input",
        `invalid datalog query in view ${view.name}: ${err instanceof Error ? err.message : String(err)}`,
        { view: view.name },
      ),
  });
  const body = template(rows, templateContext(ctx));
  return `${GENERATED_HEADER}\n\n${body.trimEnd()}\n`;
});
